version: '3'

services:

  yazio:
    image: mysql:5.7.24
    #        volumes:
    #          - "./volumes/mysql_dev:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=YazioRocks
      - MYSQL_DATABASE=yazio
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword