fos_rest:
  routing_loader:
    include_format: false
  format_listener:
    rules:
      - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
  view:
    view_response_listener:
      enabled: true